---
services:
  sonarr:
    image: braingremlin/sonarr-py:latest
    container_name: sonarr
    env_file:
      - stack.env
    volumes:
      - ${CONFIG_DIR:-config}:/config
      - ${MEDIA_DIR:-media}:/media02
    security_opt:
      - no-new-privileges:true
    ports:
      - 8989:8989
    restart: unless-stopped
